version: '3.8'

services:
  dev-pay-service:
    build: .
    ports:
      - "50051"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    #      resources:
    #        limits:
    #          cpus: '2'      # Limit to 2 CPU cores
    #          memory: '4g'   # Limit to 4GB of memory
    environment:
      - GOMAXPROCS=14
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    container_name: dev-pay-postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devpay
      PGTZ: "Asia/Tokyo"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5